### ISSUE TITLE
Integrate positive and negative sentiment detection

### ISSUE THREAD

**Issue by vnoelifant** [vnoelifant/cozmo-companion#1]
The robot should be able to have a dialogue with the user based on the user's needs (whether user would like an assistant to to generate smart responses to questions, whether the user would like emotional support, or whether the user simply wants friendly small-talk).

**Comment by vnoelifant** [comment]
Not sure what happened to Watson Tone Analyzer, but I do plan to write my own Deep Learning model to capture Tone detection, and use the Watson API for speech to text, and text to speech.

**Comment by vnoelifant** [comment]
May not even need Watson Speech to Text service anymore as Python as a Speech Recognition library. Cozmo also has a built in Text to Speech. But may continue using Watson Assistant for dialogue flow service.

**Comment by vnoelifant** [comment]
This is really probably modifying the old code that used Watson Assistant service for managing the flow of the dialogue and maintaining conversational state.

**Comment by Zaubeerer** [comment]
Did you consider using OPEN AI's Whisper API?

**Comment by Zaubeerer** [comment]
For the chatbot, you could leverage marvin: https://www.askmarvin.ai/

**Comment by vnoelifant** [comment]
I know I have heard the term Whisper but I haven't looked in detail. I will take a look, thank you! Currently I used [Watson Speech to Text](https://www.ibm.com/cloud/watson-speech-to-text?utm_content=SRCWW&p1=Search&p4=43700074359384806&p5=e&gclid=Cj0KCQjwjryjBhD0ARIsAMLvnF9TNXEEej7nloRVOWScr9J3adlXa4FVW3IWMxYaL6p-p1I5Lxt7Be4aAmWHEALw_wcB&gclsrc=aw.ds) and this method from Cozmo for text to speech  http://cozmosdk.anki.com/docs/generated/cozmo.robot.html#module-cozmo.robot. Would it be worth it to compare the different capabilities of each tool/API?

**Comment by Zaubeerer** [comment]
I would say:
- make it work
- make it right
- make it fast

So, if something already works, move on to the next challenge instead of distracting yourself by comparing different solutions :)
