### ISSUE TITLE
Add text sentiment analysis to Dialogue Flow

### ISSUE THREAD

**Issue by vnoelifant** [vnoelifant/cozmo-companion#13]

**Comment by Zaubeerer** [comment]
see other issue, you may want to consider using ChatGPT with GPT4 for sentiment analysis :)

**Comment by vnoelifant** [comment]
Yeah I wanted to try that for sure. That is, text sentiment right?

**Comment by Zaubeerer** [comment]
Yes, you can provide the transcripts to chatgpt and simply ask "how do they feel?" ;-)
