### ISSUE TITLE
Create Text Sentiment Analysis Dialogue Flow Decision Tree

### ISSUE THREAD

**Issue by vnoelifant** [vnoelifant/cozmo-companion#20]

**Comment by vnoelifant** [comment]
First go: 
Hopefully something like this works. @Zaubeerer 

![Image](https://github.com/vnoelifant/cozmo-companion/assets/43191157/a75ec710-de61-4025-b843-9f61bdd96f70)

**Comment by vnoelifant** [comment]
I next plan to see if Marvin can help me create this logic, I know they have several utilities for extracting sentiment, as well as prompt engineering.

**Comment by Zaubeerer** [comment]
Yes, this may actually just be a "one-liner", leveraging marvinAI's chatbot application:
https://www.askmarvin.ai/src/docs/components/ai_application/#chatbot 


Looking forward to seeing your results 🙏
