### ISSUE TITLE
Make feedback question detection more general

### ISSUE THREAD

**Issue by vnoelifant** [vnoelifant/cozmo-companion#30]

**Comment by vnoelifant** [comment]
Make feedback question detection more general (e.g. with ai_function that checks if a feedback question is already included in the chatgpt response). https://github.com/vnoelifant/cozmo-companion/pull/26#discussion_r1375762462

**Comment by vnoelifant** [comment]
Wondering if it is better to have something like this in the `_generate_response` method from [assistant.py](https://github.com/vnoelifant/cozmo-companion/blob/ai-function-feedback/src/cozmo_companion/assistant.py)
```
            # If there's a feedback inquiry, append it to the chatbot's response
            feedback_inquiry = get_feedback_inquiry(gpt_prompt)
            if feedback_inquiry and feedback_inquiry not in gpt_response:
                gpt_response += feedback_inquiry
```

Or what I currently have:
```
            # If there is a request for feedback inquiry and inquiry tokens don't already exist in gpt response, append 
            # specific feedback inquiry to gpt response
            feedback_inquiry_bot_tokens = ["help", "?"]
            if feedback_inquiry and not is_tokens_in_gpt_response(gpt_response, feedback_inquiry_bot_tokens):
                gpt_response += feedback_inquiry
```

The first one seems to be just checking if the exact phrase is matched, but think it would be better to handle the potentially different but similar phrases (like if phrase contains any token from a list). @Zaubeerer .

**Comment by vnoelifant** [comment]
@Zaubeerer instead if passing in a list of tokens to the AI function, I kept it even more high level, to allow the AI to be able to predict the output of the function based on the docstring text and type hints, per Marvin design philosophy of functions. 

```
@ai_fn
def is_feedback_inquiry_present(bot_text: str) -> bool:
    """
    Analyzes the bot's response to determine if it contains a feedback inquiry.

    The function leverages natural language understanding to interpret the text and
    identify feedback-related phrases, taking into account the context and subtleties
    of the conversation. It examines the text of a chatbot's response to detect if
    it includes phrases or questions that are seeking feedback from the user. Common
    examples of feedback inquiries might include direct questions like "Did that help
    you?" or "Do you want to know more?" as well as subtle cues such as the presence
    of a question mark (?) at the end of a statement.

    Args:
        bot_text: The text of the response provided by the chatbot. This can range
        from answers and statements to jokes or informational content.

    Returns:
        bool: Indicates whether the bot's response includes a feedback inquiry.
            - True: If phrases or questions seeking feedback are found, indicating
                an active attempt by the bot to engage with the user or confirm
                understanding.
            - False: If no feedback-seeking phrases or questions are detected,
                suggesting a straightforward response without solicitation for feedback.
    """
    return False  # Dummy return value for type checking
 ```
    
**Guidance from GPT:**
Considerations:
AI's Predictive Power: By detailing the expected behavior in the docstring, you leverage the AI's capability to understand and interpret the request based on natural language processing.

Flexibility: This approach is more flexible as it doesn't rely on a predefined list of tokens. The AI can potentially recognize a wider range of feedback-related phrases.

Clarity and Documentation: Ensure that the docstring is clear and descriptive about the function's purpose and the kind of phrases it should look for. This clarity is crucial for the AI to make accurate predictions.

Testing and Refinement: As with any AI-powered functionality, it's important to test and refine the approach based on actual use cases and feedback, adjusting the description and approach as needed to achieve the desired outcomes.

This revised approach aligns with the principles of Marvin AI, allowing the AI to utilize its language model to predict the function's output based on a well-defined description and input parameters.

**Comment by Zaubeerer** [comment]
Did you accidentally close this issue?

Love your question and your solution, looking forward to discuss it if necessary!

**Comment by vnoelifant** [comment]
> Did you accidentally close this issue?
> 
> Love your question and your solution, looking forward to discuss it if necessary!

I think I have it set to close if the associated PR closes.
