### ISSUE TITLE
Create template code for Speech Emotion Recognizer

### ISSUE THREAD

**Issue by vnoelifant** [vnoelifant/cozmo-companion#4]
In past project in college, I utilized Watson Tone Analyzer for detecting emotion. In this iteration, I'd like to create my own deep learning model that is able to detect speech, and predict user's emotion via the model. Preliminary research will explore Deep learning APIs (i.e. Keras) and audio analysis packages like Python's [Librosa](https://librosa.org/doc/latest/index.html).

**Comment by Zaubeerer** [comment]
You can take a shortcut and first try sentiment analysis using ChatGPT (with GPT4!).

Like such, you can get something running quickly and implement related functionality.

Later, you can always implement your own model, if GPT4 is not sufficient or if you just want to learn sth new ;-)

**Comment by vnoelifant** [comment]
That sounds like a good plan! I was thinking the same. Get something up and running working quickly, and maybe later learn how to write a model. This was actually intended to be for tone (voice) emotion detection (do you know of any tool I can use for that?) Does Chat GPT only do the text sentiment?

**Comment by Zaubeerer** [comment]
Yeah, you can first transcribe, e.g with OPEN AI Whisper API, then send that text to GPT4 with a prompt like.

```
Here is something a person sad:

"""
transcript
"""

How does the person feel like?
```

**Comment by Zaubeerer** [comment]
In the code clinic "AI-Driven Development: Part 2", I shared a cheat sheet with some hints on how to optimize the prompts for sentiment analysis ;-)

see: https://pybites.mykajabi.com/products/pybites-coaching-calls-2/categories/3469727/posts/2167910988
